<?php
/**
 * ChartsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Topal REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Topal\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Topal\Client\ApiException;
use Topal\Client\Configuration;
use Topal\Client\HeaderSelector;
use Topal\Client\ObjectSerializer;

/**
 * ChartsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChartsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'chartsGetCCStatement' => [
            'application/json',
        ],
        'chartsGetFormulaList' => [
            'application/json',
        ],
        'chartsGetFormulaStatement' => [
            'application/json',
        ],
        'chartsGetStatement' => [
            'application/json',
        ],
        'chartsValidateFormula' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation chartsGetCCStatement
     *
     * Gets accouht cost cetner balance witin given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $account_code account_code (required)
     * @param  string $cost_center_code cost_center_code (required)
     * @param  \DateTime $date date (required)
     * @param  string $period_name period_name (required)
     * @param  int $periods_count periods_count (required)
     * @param  string $client_id client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetCCStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Topal\Client\Model\Statement
     */
    public function chartsGetCCStatement($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetCCStatement'][0])
    {
        list($response) = $this->chartsGetCCStatementWithHttpInfo($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, $contentType);
        return $response;
    }

    /**
     * Operation chartsGetCCStatementWithHttpInfo
     *
     * Gets accouht cost cetner balance witin given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $account_code (required)
     * @param  string $cost_center_code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetCCStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Topal\Client\Model\Statement, HTTP status code, HTTP response headers (array of strings)
     */
    public function chartsGetCCStatementWithHttpInfo($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetCCStatement'][0])
    {
        $request = $this->chartsGetCCStatementRequest($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Topal\Client\Model\Statement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Topal\Client\Model\Statement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Topal\Client\Model\Statement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Topal\Client\Model\Statement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Topal\Client\Model\Statement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chartsGetCCStatementAsync
     *
     * Gets accouht cost cetner balance witin given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $account_code (required)
     * @param  string $cost_center_code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetCCStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetCCStatementAsync($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetCCStatement'][0])
    {
        return $this->chartsGetCCStatementAsyncWithHttpInfo($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chartsGetCCStatementAsyncWithHttpInfo
     *
     * Gets accouht cost cetner balance witin given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $account_code (required)
     * @param  string $cost_center_code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetCCStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetCCStatementAsyncWithHttpInfo($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetCCStatement'][0])
    {
        $returnType = '\Topal\Client\Model\Statement';
        $request = $this->chartsGetCCStatementRequest($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chartsGetCCStatement'
     *
     * @param  string $account_code (required)
     * @param  string $cost_center_code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetCCStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chartsGetCCStatementRequest($account_code, $cost_center_code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetCCStatement'][0])
    {

        // verify the required parameter 'account_code' is set
        if ($account_code === null || (is_array($account_code) && count($account_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_code when calling chartsGetCCStatement'
            );
        }

        // verify the required parameter 'cost_center_code' is set
        if ($cost_center_code === null || (is_array($cost_center_code) && count($cost_center_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cost_center_code when calling chartsGetCCStatement'
            );
        }

        // verify the required parameter 'date' is set
        if ($date === null || (is_array($date) && count($date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date when calling chartsGetCCStatement'
            );
        }

        // verify the required parameter 'period_name' is set
        if ($period_name === null || (is_array($period_name) && count($period_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $period_name when calling chartsGetCCStatement'
            );
        }

        // verify the required parameter 'periods_count' is set
        if ($periods_count === null || (is_array($periods_count) && count($periods_count) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $periods_count when calling chartsGetCCStatement'
            );
        }

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling chartsGetCCStatement'
            );
        }


        $resourcePath = '/api/v1/clients/{clientId}/charts/statement/costcenters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $account_code,
            'accountCode', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cost_center_code,
            'costCenterCode', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $period_name,
            'periodName', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $periods_count,
            'periodsCount', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($client_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clientId' . '}',
                ObjectSerializer::toPathValue($client_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chartsGetFormulaList
     *
     * Gets list of MIS formulas trees of client
     *
     * @param  string $client_id client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaList'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Topal\Client\Model\MisFormulaTree[]
     */
    public function chartsGetFormulaList($client_id, string $contentType = self::contentTypes['chartsGetFormulaList'][0])
    {
        list($response) = $this->chartsGetFormulaListWithHttpInfo($client_id, $contentType);
        return $response;
    }

    /**
     * Operation chartsGetFormulaListWithHttpInfo
     *
     * Gets list of MIS formulas trees of client
     *
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaList'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Topal\Client\Model\MisFormulaTree[], HTTP status code, HTTP response headers (array of strings)
     */
    public function chartsGetFormulaListWithHttpInfo($client_id, string $contentType = self::contentTypes['chartsGetFormulaList'][0])
    {
        $request = $this->chartsGetFormulaListRequest($client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Topal\Client\Model\MisFormulaTree[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Topal\Client\Model\MisFormulaTree[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Topal\Client\Model\MisFormulaTree[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Topal\Client\Model\MisFormulaTree[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Topal\Client\Model\MisFormulaTree[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chartsGetFormulaListAsync
     *
     * Gets list of MIS formulas trees of client
     *
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetFormulaListAsync($client_id, string $contentType = self::contentTypes['chartsGetFormulaList'][0])
    {
        return $this->chartsGetFormulaListAsyncWithHttpInfo($client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chartsGetFormulaListAsyncWithHttpInfo
     *
     * Gets list of MIS formulas trees of client
     *
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetFormulaListAsyncWithHttpInfo($client_id, string $contentType = self::contentTypes['chartsGetFormulaList'][0])
    {
        $returnType = '\Topal\Client\Model\MisFormulaTree[]';
        $request = $this->chartsGetFormulaListRequest($client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chartsGetFormulaList'
     *
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chartsGetFormulaListRequest($client_id, string $contentType = self::contentTypes['chartsGetFormulaList'][0])
    {

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling chartsGetFormulaList'
            );
        }


        $resourcePath = '/api/v1/clients/{clientId}/charts/formula/templates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($client_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clientId' . '}',
                ObjectSerializer::toPathValue($client_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chartsGetFormulaStatement
     *
     * Gets period values of given formula  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $formula formula (required)
     * @param  \DateTime $date date (required)
     * @param  string $period_name period_name (required)
     * @param  int $periods_count periods_count (required)
     * @param  string $client_id client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Topal\Client\Model\FormulaStatement
     */
    public function chartsGetFormulaStatement($formula, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetFormulaStatement'][0])
    {
        list($response) = $this->chartsGetFormulaStatementWithHttpInfo($formula, $date, $period_name, $periods_count, $client_id, $contentType);
        return $response;
    }

    /**
     * Operation chartsGetFormulaStatementWithHttpInfo
     *
     * Gets period values of given formula  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $formula (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Topal\Client\Model\FormulaStatement, HTTP status code, HTTP response headers (array of strings)
     */
    public function chartsGetFormulaStatementWithHttpInfo($formula, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetFormulaStatement'][0])
    {
        $request = $this->chartsGetFormulaStatementRequest($formula, $date, $period_name, $periods_count, $client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Topal\Client\Model\FormulaStatement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Topal\Client\Model\FormulaStatement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Topal\Client\Model\FormulaStatement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Topal\Client\Model\FormulaStatement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Topal\Client\Model\FormulaStatement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chartsGetFormulaStatementAsync
     *
     * Gets period values of given formula  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $formula (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetFormulaStatementAsync($formula, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetFormulaStatement'][0])
    {
        return $this->chartsGetFormulaStatementAsyncWithHttpInfo($formula, $date, $period_name, $periods_count, $client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chartsGetFormulaStatementAsyncWithHttpInfo
     *
     * Gets period values of given formula  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $formula (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetFormulaStatementAsyncWithHttpInfo($formula, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetFormulaStatement'][0])
    {
        $returnType = '\Topal\Client\Model\FormulaStatement';
        $request = $this->chartsGetFormulaStatementRequest($formula, $date, $period_name, $periods_count, $client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chartsGetFormulaStatement'
     *
     * @param  string $formula (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetFormulaStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chartsGetFormulaStatementRequest($formula, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetFormulaStatement'][0])
    {

        // verify the required parameter 'formula' is set
        if ($formula === null || (is_array($formula) && count($formula) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $formula when calling chartsGetFormulaStatement'
            );
        }

        // verify the required parameter 'date' is set
        if ($date === null || (is_array($date) && count($date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date when calling chartsGetFormulaStatement'
            );
        }

        // verify the required parameter 'period_name' is set
        if ($period_name === null || (is_array($period_name) && count($period_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $period_name when calling chartsGetFormulaStatement'
            );
        }

        // verify the required parameter 'periods_count' is set
        if ($periods_count === null || (is_array($periods_count) && count($periods_count) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $periods_count when calling chartsGetFormulaStatement'
            );
        }

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling chartsGetFormulaStatement'
            );
        }


        $resourcePath = '/api/v1/clients/{clientId}/charts/formula';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $formula,
            'formula', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $period_name,
            'periodName', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $periods_count,
            'periodsCount', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($client_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clientId' . '}',
                ObjectSerializer::toPathValue($client_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chartsGetStatement
     *
     * Gets list of COA balances within given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $code code (required)
     * @param  \DateTime $date date (required)
     * @param  string $period_name period_name (required)
     * @param  int $periods_count periods_count (required)
     * @param  string $client_id client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Topal\Client\Model\Statement
     */
    public function chartsGetStatement($code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetStatement'][0])
    {
        list($response) = $this->chartsGetStatementWithHttpInfo($code, $date, $period_name, $periods_count, $client_id, $contentType);
        return $response;
    }

    /**
     * Operation chartsGetStatementWithHttpInfo
     *
     * Gets list of COA balances within given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetStatement'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Topal\Client\Model\Statement, HTTP status code, HTTP response headers (array of strings)
     */
    public function chartsGetStatementWithHttpInfo($code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetStatement'][0])
    {
        $request = $this->chartsGetStatementRequest($code, $date, $period_name, $periods_count, $client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Topal\Client\Model\Statement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Topal\Client\Model\Statement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Topal\Client\Model\Statement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Topal\Client\Model\Statement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Topal\Client\Model\Statement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chartsGetStatementAsync
     *
     * Gets list of COA balances within given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetStatementAsync($code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetStatement'][0])
    {
        return $this->chartsGetStatementAsyncWithHttpInfo($code, $date, $period_name, $periods_count, $client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chartsGetStatementAsyncWithHttpInfo
     *
     * Gets list of COA balances within given period  periods: year, quarter, month, day  maximum periods count - 12
     *
     * @param  string $code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsGetStatementAsyncWithHttpInfo($code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetStatement'][0])
    {
        $returnType = '\Topal\Client\Model\Statement';
        $request = $this->chartsGetStatementRequest($code, $date, $period_name, $periods_count, $client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chartsGetStatement'
     *
     * @param  string $code (required)
     * @param  \DateTime $date (required)
     * @param  string $period_name (required)
     * @param  int $periods_count (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsGetStatement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chartsGetStatementRequest($code, $date, $period_name, $periods_count, $client_id, string $contentType = self::contentTypes['chartsGetStatement'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling chartsGetStatement'
            );
        }

        // verify the required parameter 'date' is set
        if ($date === null || (is_array($date) && count($date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date when calling chartsGetStatement'
            );
        }

        // verify the required parameter 'period_name' is set
        if ($period_name === null || (is_array($period_name) && count($period_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $period_name when calling chartsGetStatement'
            );
        }

        // verify the required parameter 'periods_count' is set
        if ($periods_count === null || (is_array($periods_count) && count($periods_count) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $periods_count when calling chartsGetStatement'
            );
        }

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling chartsGetStatement'
            );
        }


        $resourcePath = '/api/v1/clients/{clientId}/charts/statement';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $period_name,
            'periodName', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $periods_count,
            'periodsCount', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($client_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clientId' . '}',
                ObjectSerializer::toPathValue($client_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chartsValidateFormula
     *
     * Validates given formula for errors
     *
     * @param  string $formula formula (required)
     * @param  string $client_id client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsValidateFormula'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function chartsValidateFormula($formula, $client_id, string $contentType = self::contentTypes['chartsValidateFormula'][0])
    {
        list($response) = $this->chartsValidateFormulaWithHttpInfo($formula, $client_id, $contentType);
        return $response;
    }

    /**
     * Operation chartsValidateFormulaWithHttpInfo
     *
     * Validates given formula for errors
     *
     * @param  string $formula (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsValidateFormula'] to see the possible values for this operation
     *
     * @throws \Topal\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function chartsValidateFormulaWithHttpInfo($formula, $client_id, string $contentType = self::contentTypes['chartsValidateFormula'][0])
    {
        $request = $this->chartsValidateFormulaRequest($formula, $client_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chartsValidateFormulaAsync
     *
     * Validates given formula for errors
     *
     * @param  string $formula (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsValidateFormula'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsValidateFormulaAsync($formula, $client_id, string $contentType = self::contentTypes['chartsValidateFormula'][0])
    {
        return $this->chartsValidateFormulaAsyncWithHttpInfo($formula, $client_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chartsValidateFormulaAsyncWithHttpInfo
     *
     * Validates given formula for errors
     *
     * @param  string $formula (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsValidateFormula'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chartsValidateFormulaAsyncWithHttpInfo($formula, $client_id, string $contentType = self::contentTypes['chartsValidateFormula'][0])
    {
        $returnType = 'string';
        $request = $this->chartsValidateFormulaRequest($formula, $client_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chartsValidateFormula'
     *
     * @param  string $formula (required)
     * @param  string $client_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chartsValidateFormula'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chartsValidateFormulaRequest($formula, $client_id, string $contentType = self::contentTypes['chartsValidateFormula'][0])
    {

        // verify the required parameter 'formula' is set
        if ($formula === null || (is_array($formula) && count($formula) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $formula when calling chartsValidateFormula'
            );
        }

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling chartsValidateFormula'
            );
        }


        $resourcePath = '/api/v1/clients/{clientId}/charts/formula/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $formula,
            'formula', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($client_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clientId' . '}',
                ObjectSerializer::toPathValue($client_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
