<?php
/**
 * TransactionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Topal REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Topal\Client\Test\Api;

use \Topal\Client\Configuration;
use \Topal\Client\ApiException;
use \Topal\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for transactionsCreatePosting
     *
     * create posting based on optinal parameters.
     *
     */
    public function testTransactionsCreatePosting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsDelete
     *
     * delete transaction.
     *
     */
    public function testTransactionsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsDeleteDocument
     *
     * delete document.
     *
     */
    public function testTransactionsDeleteDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsDownloadDocument
     *
     * download document.
     *
     */
    public function testTransactionsDownloadDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsGet
     *
     * get transaction by id.
     *
     */
    public function testTransactionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsGetByDocNum
     *
     * get transaction by docNum.
     *
     */
    public function testTransactionsGetByDocNum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsGetPendingDocuments
     *
     * get not procssed documents from dms.
     *
     */
    public function testTransactionsGetPendingDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsGetVatPosting
     *
     * create posting with calculated vat amounts.
     *
     */
    public function testTransactionsGetVatPosting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsGet_0
     *
     * get all transactions within fiscal year.
     *
     */
    public function testTransactionsGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsLinkDocument
     *
     * link document.
     *
     */
    public function testTransactionsLinkDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsNew
     *
     * creates new transaction of given type.
     *
     */
    public function testTransactionsNew()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsPost
     *
     * saves transaction.
     *
     */
    public function testTransactionsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transactionsUpload
     *
     * save  document to DMS as unrecognized transaction.
     *
     */
    public function testTransactionsUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
